### PR TITLE
[WIP] B2 Command line utility to work with SRCS files

### PR DESCRIPTION
**Pull request by petrabarus**
- [x] Convert to git
- [x] List key snapshot, patch snapshots and their addresses
- [x] Extract key snapshot to folder

### CODE REVIEW

**Comment by petrabarus** [comment]
The list command will look like this for now.

```
java -jar build/libs/dev-sourcecode-record-all.jar list --input /tmp/samplesnapshot2.srcs 
Snapshot #0: 
	Time Jan 1, 1970 7:00:00 AM
Snapshot #1: 
	Time Jan 1, 1970 7:00:01 AM
Snapshot #2: 
	Time Jan 1, 1970 7:00:02 AM
Snapshot #3: 
	Time Jan 1, 1970 7:00:03 AM
Snapshot #4: 
	Time Jan 1, 1970 7:00:04 AM
```

**Comment by julianghionoiu** [comment]
Hey Petra, I like the way the commands are starting to come together.

The purpose of these commands is to be able to debug when things go wrong so it is ok to include any technical information that could help.

Here is some feedback on the `list` command. I think it should:
- contain the snapshot address within the file
- contain the snapshot type (KEY, PATCH)
- display the time as seconds (do not translate to timestamp)
- size and checksum of snapshot

On the time, we are not going to track absolute timestamps, the timestamps will be relative. This follows the same pattern as MP4. It might be useful to have a special header at the beginning of the file to store the date of the recording and some other metadata. (not part of this iteration I have created B4)

**Comment by petrabarus** [comment]
@julianghionoiu I finished the list command. The result should be like this

```
Snapshot #0: 
	Offset    0
	Type      KEY
	Time      0s
	Size      181b
	Checksum  bd86407dd97c2327450f694438b339a99df554ed

Snapshot #1: 
	Offset    181
	Type      PATCH
	Time      1s
	Size      178b
	Checksum  f51207512e09dba4ac14fc8ad7e18fcb9371de86

Snapshot #2: 
	Offset    359
	Type      PATCH
	Time      2s
	Size      224b
	Checksum  9d43842df87a1d65eb58752b4e306666de9f9872

Snapshot #3: 
	Offset    583
	Type      KEY
	Time      3s
	Size      423b
	Checksum  493affe19f268118b43fef0bd106270868c51be9

Snapshot #4: 
	Offset    1,006
	Type      PATCH
	Time      4s
	Size      225b
	Checksum  8d3dfec4dbd1591da79084ff21b477bcd4bf9e31
```

As for size, should I put only the payload or with header? The one above is with header.

**Comment by petrabarus** [comment]
Added `export` command. Somewhat a bit buggy. Will create tests for this.

The format is like this

```
java -jar build/libs/dev-sourcecode-record-all.jar export \
    --input /tmp/samplesnapshot2.srcs \
    --output /tmp/testexport \
    --time 1
```

**Review by julianghionoiu — APPROVED** [review]

**Pull request merged**
