### PR TITLE
Stabilise build

### PR DESCRIPTION
**Pull request by julianghionoiu**
See `acceptance.CanRecordSourceCodeAccTest#should_be_able_to_record_history_at_a_given_rate` for the failure.

### CODE REVIEW

**Comment by petrabarus** [comment]
Will rebase this from `master` after https://github.com/julianghionoiu/dev-sourcecode-record/pull/12

**Comment by petrabarus** [comment]
@julianghionoiu please review.

**Review by petrabarus — APPROVED** [review]
The removed file in  key snapshot restoration is now committed using `git rm`

**Comment by julianghionoiu** [comment]
Nice!

**Pull request merged**
