### PR TITLE
Add the ability to wake up recording thread and trigger a snapshot

### PR DESCRIPTION
**Pull request by julianghionoiu**
This is the API to trigger a tagged event.

### CODE REVIEW

**Comment by petrabarus** [comment]
I rebased this from master

**Review by petrabarus — APPROVED** [review]
looks good to me.

**Comment by petrabarus** [comment]
@julianghionoiu need review

**Review by julianghionoiu — COMMENTED** [review]
The tagging part looks good.

The second part of this feature is to be able to export the tagged snapshot as Git tags when converting to git.

**Comment by petrabarus** [comment]
@julianghionoiu i missed that. just added in the newest commit https://github.com/julianghionoiu/dev-sourcecode-record/pull/11/commits/b2247c586f79f2f8e33c2ca4264cad2603cb0324

**Comment by petrabarus** [comment]
Sorry I misread git tag as git commit.

**Comment by julianghionoiu** [comment]
Looks good. This is what I had in mind.

Out of curiosity, do you know if there are any restrictions on the git tag name? Any forbidden characters?

**Comment by petrabarus** [comment]
quick search shows this https://git-scm.com/docs/git-check-ref-format

```


Git imposes the following rules on how references are named:

    They can include slash / for hierarchical (directory) grouping, but no slash-separated component can begin with a dot . or end with the sequence .lock.

    They must contain at least one /. This enforces the presence of a category like heads/, tags/ etc. but the actual names are not restricted. If the --allow-onelevel option is used, this rule is waived.

    They cannot have two consecutive dots .. anywhere.

    They cannot have ASCII control characters (i.e. bytes whose values are lower than \040, or \177 DEL), space, tilde ~, caret ^, or colon : anywhere.

    They cannot have question-mark ?, asterisk *, or open bracket [ anywhere. See the --refspec-pattern option below for an exception to this rule.

    They cannot begin or end with a slash / or contain multiple consecutive slashes (see the --normalize option below for an exception to this rule)

    They cannot end with a dot ..

    They cannot contain a sequence @{.

    They cannot be the single character @.

    They cannot contain a \.

```

**Pull request merged**
